apiVersion: v1
kind: Service
metadata:
  name: go-kube
spec:
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-kube
  annotations:
    keel.sh/policy: "glob:dev-*"
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: go-kube
          image: runq/go-kube:dev-0ca740e