apiVersion: v1
kind: Namespace
metadata:
  name: go-kube-production
---
apiVersion: v1
kind: Service
metadata:
  name: go-kube
  namespace: go-kube-production
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: go-kube
  sessionAffinity: ClientIP
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    keel.sh/policy: all
  name: go-kube
  namespace: go-kube-production
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go-kube
  template:
    metadata:
      labels:
        app: go-kube
      name: go-kube
    spec:
      containers:
      - image: runq/go-kube:0.1.0
        imagePullPolicy: IfNotPresent
        name: go-kube
        ports:
        - containerPort: 8080
          protocol: TCP
